# MAPPING FOR GENERATING THE TOWN
HEXA_PIZZA = "0"

HOUSE_ENTRANCE_LEFT = "1"
HOUSE_ENTRANCE_RIGHT = "2"
HOUSE_ENTRANCE_TOP = "3"
HOUSE_ENTRANCE_BOTTOM = "4"

ROAD_STRAIGHT_BOTTOM_TOP = "A"
ROAD_STRAIGHT_LEFT_RIGHT = "B"
ROAD_CURVE_TOP_LEFT = "C"
ROAD_CURVE_TOP_RIGHT = "D"
ROAD_CURVE_BOTTOM_LEFT = "E"
ROAD_CURVE_BOTTOM_RIGHT = "F"
ROAD_CROSSROADS = "G"
ROAD_BRIDGE_TOP_BOTTOM = "H"
ROAD_BRIDGE_LEFT_RIGHT = "I"

SCENERY_FOREST_VARIATION_1 = "+"
SCENERY_FOREST_VARIATION_2 = "-"
SCENERY_MEADOW_1 = "*"
SCENERY_MEADOW_2 = "#"
SCENERY_RIVER_TOP_BOTTOM = "!"
SCENERY_RIVER_LEFT_RIGHT = "?"

DAY_IMAGE = "day"
NIGHT_IMAGE = "night"

# Lookup dict.
MAPPING_CHAR_FILENAMES = {
	HOUSE_ENTRANCE_LEFT: {
		"day": "HOUSE_ENTRANCE_LEFT.png",
		"night": "HOUSE_ENTRANCE_LEFT.png"
		},
	HOUSE_ENTRANCE_RIGHT: {
		"day": "HOUSE_ENTRANCE_RIGHT.png",
		"night": "HOUSE_ENTRANCE_RIGHT.png"
		},
	HOUSE_ENTRANCE_BOTTOM: {
		"day": "HOUSE_ENTRANCE_BOTTOM.png",
		"night": "HOUSE_ENTRANCE_BOTTOM.png"
		},
	HOUSE_ENTRANCE_TOP: {
		"day": "HOUSE_ENTRANCE_TOP.png",
		"night": "HOUSE_ENTRANCE_TOP.png"
		},
	ROAD_STRAIGHT_LEFT_RIGHT: {
		"day": "ROAD_STRAIGHT_LEFT_RIGHT_DAY.png",
		"night": "ROAD_STRAIGHT_LEFT_RIGHT_DAY.png"
		},
	ROAD_STRAIGHT_BOTTOM_TOP: {
		"day": "ROAD_STRAIGHT_BOTTOM_TOP_DAY.png",
		"night": "ROAD_STRAIGHT_BOTTOM_TOP_DAY.png"
		},
	ROAD_CURVE_BOTTOM_RIGHT: {
		"day": "ROAD_CURVE_BOTTOM_RIGHT_DAY.png",
		"night": "ROAD_CURVE_BOTTOM_RIGHT_DAY.png"
		},
	ROAD_CURVE_BOTTOM_LEFT: {
		"day": "ROAD_CURVE_BOTTOM_LEFT_DAY.png",
		"night": "ROAD_CURVE_BOTTOM_LEFT_DAY.png"
		},
	ROAD_CURVE_TOP_LEFT: {
		"day": "ROAD_CURVE_TOP_LEFT_DAY.png",
		"night": "ROAD_CURVE_TOP_LEFT_DAY.png"
		},
	ROAD_CURVE_TOP_RIGHT: {
		"day": "ROAD_CURVE_TOP_RIGHT_DAY.png",
		"night": "ROAD_CURVE_TOP_RIGHT_DAY.png"
		},
	SCENERY_FOREST_VARIATION_1: {
		"day": "SCENERY_FOREST_VARIATION_1_DAY.png",
		"night": "SCENERY_FOREST_VARIATION_1_DAY.png"
		},
	SCENERY_FOREST_VARIATION_2: {
		"day": "SCENERY_FOREST_VARIATION_2_DAY.png",
		"night": "SCENERY_FOREST_VARIATION_2_DAY.png"
		}
	}

# Dimensions of a single map tile always are the same.
MAP_TILE_SIZE_WIDTH = 200 # px
MAP_TILE_SIZE_HEIGHT = 200 # px